Yolean/kubernetes-kafka

20dns.yml
I noticed this small discrepancy in the comment. the namespace should be `kafka` instead of `default`.
=> correct namespace in DNS name

zookeeper/README.md
Updating README so that `kubectl` commands reflect the namespace changes
=> README to reflect namespace changes

50kafka.yml, docker-kafka-persistent/Dockerfile, docker-kafka-persistent/config/server.properties
We use Kafka for Event Sourcing use cases with relatively small data volumes and wish to keep logs "forever".
=> Publish Kafka image geared towards persistent storage

zookeeper/20zoo-service.yml
Added the zookeeper/zoo service to the kafka namespace as it was incorrectly being placed in default.
=> Added missing namespace from zoo service.

50kafka.yml, README.md
Compatible with https://github.com/Yolean/kubernetes-monitoring and probably most other Kubernetes + Prometheus setups. Should be useful with the Grafana dashboard from https://github.com/rama-nallamilli/kafka-prometheus-monitoring/blob/master/dashboards/Kafka.json.
Unlike https://github.com/rama-nallamilli/kafka-prometheus-monitoring/blob/master/prometheus-jmx-exporter/confd/templates/kafka.yml.tmpl I saw no reason to make the JMX_PORT configurable, as there's no need to export it outside the pod (a benefit with k8s compared to docker-compose). To tweak configuration I suggest a ConfigMap with the metrics setup.
=> Add metrics exporter for Prometheus

50kafka.yml, zookeeper/10zookeeper-config.yml, zookeeper/50zoo.yml
The Kafka distribution already includes Zookeeper's main, so there's no need for us to pull another image.
The README.md used to say:
> If you lose your zookeeper cluster, kafka will be unaware that persisted topics exist. The data is still there, but you need to re-create topics.
But that's a risky assumption if you have partitioning, which we aim to improve at with #30.
=> Use persistent volumes for Zookeeper, and use the Kafka image

zookeeper/10zookeeper-config.yml, zookeeper/20pzoo-service.yml, zookeeper/21zoo-service.yml, zookeeper/50pzoo.yml, zookeeper/51zoo.yml
Goal:
* With a cluster spanning two or three availability zones, be able to form a quorum even if only one zone is up.
* If all zookeeper pods die, be able to start them up again with kafka's metadata intact.
Addresses a weakness with PV and multi-zone clusters identified in #33. For evaluation with #30.
=> Suggest a mix of persistent and ephemeral data to improve reliability across zones

10broker-config.yml, 50kafka.yml, update-kafka-image.sh
This is to facilitate advanced per-pod config like https://github.com/Yolean/kubernetes-kafka/pull/41. We'll need a script to modify `server.properties` prior to `./bin/kafka-server-start.sh` execution. That could be through a custom entrypoint - which introduces tight coupling to a specific image build - or through an init container that mounts the same config volume and edits the config file. Files in ConfigMap volumes are editable by init containers. A sample image for such an init container might come out of https://github.com/solsson/dockerfiles/pull/8.
=> Use config map for broker configuration

10broker-config.yml, 50kafka.yml, zookeeper/10zookeeper-config.yml, zookeeper/50pzoo.yml, zookeeper/51zoo.yml
Next step after mounting config in #46. Idea raised in https://github.com/Yolean/kubernetes-kafka/pull/41#issuecomment-316277390.
Now we can see where we find config most maintainable, and extendable:
* Edit the .properties in the ConfigMap
* Add `--override`
* Patch .properties through init container
=> Use init container for per-pod config

10broker-config.yml, 50kafka.yml, test/11topic-create-test1.yml, test/12topic-create-test2.yml, test/21consumer-test1.yml, test/31producer-test1.yml, test/99testclient.yml, update-kafka-image.sh, zookeeper/10zookeeper-config.yml, zookeeper/50pzoo.yml, zookeeper/51zoo.yml
We're adding ever more `--override` commands, as seen in for example https://github.com/Yolean/kubernetes-kafka/issues/13#issuecomment-317749903. #41 will require some amazing bash one-line stuff, or that we use a script to modify the properties file. To keep options open here I'm (re-)introducing a ConfigMap for Kafka server start.
With this change we have to reflect on the assumptions we make about the Kafka image. Choice of shell and paths affect Kubernetes manifests. Choice of base image (contestant are Debian and Alpine) profoundly affects how the projects matures WRT for example resource limits. Maturity with Alpine would mean we risk lots if regressions if we switch. Thus I wanted to do some image work, as motivated https://github.com/solsson/dockerfiles/pull/5.
I'm still hesitant …
=> Mount config and use debian based image

10broker-config.yml
Will happen in the October release, so there's no reason to keep it disabled now with the merge of the #30 refactoring and retesting.
https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=71764913
=> Enable topic deletion option by default

11confluent-config.yml, 61schemas.yml, 71rest.yml, test/rest-curl.yml
See arguments in https://github.com/solsson/dockerfiles/pull/13
The test's sample curl commands based on http://docs.confluent.io/current/kafka-rest/docs/intro.html#quickstart work now. After merge #45 will have to convert this to an actual test.
=> Use config files and kafka-jre based build for Confluent Platform services

10broker-config.yml, 50kafka.yml, rbac-namespace-default/node-reader.yml
Important when you have zones > 1 and kafka replicas > zones.
- http://kafka.apache.org/documentation/#basic_ops_racks
- https://kubernetes.io/docs/admin/multiple-zones/#nodes-are-labeled
- https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#interlude-built-in-node-labels
- https://stackoverflow.com/questions/36690446/inject-node-labels-into-kubernetes-pod
- https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api
- https://github.com/kubernetes/kubernetes/pull/27880#issuecomment-278999615
=> Multizone rack awareness

README.md
... or should we switch back to manually provisioned volumes, and find some other way to deal with [multiple zones](https://kubernetes.io/docs/admin/multiple-zones/#volume-affinity).
=> Set provisioned volumes to Retain by default

events-kube/topic-ops-kube-events-all-json.yml
Silly change, but 0.8 days is very short.
Google helped me verify the math.
=> Fix retention from 0.8 days to 8 days

zookeeper/10zookeeper-config.yml, zookeeper/50pzoo.yml
Help wanted in order to improve #49. I can get JVM stats, but nothing [org.apache.ZooKeeperService](https://zookeeper.apache.org/doc/trunk/zookeeperJMX.html#ch_reference).
=> Try to get meaningful metrics from Zookeeper

10broker-config.yml, 50kafka.yml, outside-services/outside-0.yml, outside-services/outside-1.yml, outside-services/outside-2.yml
This is my interpretation of a baseline for different type of clusters, from #13.
The new pod label is low-risk, as are the services. The new directives in `server.properties` need more testing. Might de-stabilize regular inside access.
I've tested this only on minikube so far:
* Internal access still works, without changes, according to [test/basic-with-kafkacat.yml](https://github.com/Yolean/kubernetes-kafka/blob/outside-services/test/basic-with-kafkacat.yml)
* Outside access:
```
BOOTSTRAP=$(minikube ip):32400,$(minikube ip):32401,$(minikube ip):32402
docker run --rm -t solsson/kafkacat -C -b $BOOTSTRAP -t test-basic-with-kafkacat -o -10
```
Outside+minikube is interesting as a local development setup for Kafka services. Production clusters on the other hand will probably always need …
=> Outside (i.e. cluster-external) access through per-broker Service

30bootstrap-service.yml, test/basic-with-kafkacat.yml
This looks useful but I'm hesitant to merge to master due to #21, which we dealt with by removing the service in #30.
I fail to figure out how to test, let alone enforce, that this service is only used for the initial connection but not for actual consumption or production. Clients should discover brokers through this service, but not suffer from the round-robin nature of it. A danger is that when developing with 1 replica, #44 for example, there is no round-robin and thus no such issues.
=> Addon: bootstrap.kafka service with current brokers as endpoint

yahoo-kafka-manager/kafka-manager-service.yml, yahoo-kafka-manager/kafka-manager.yml
https://github.com/yahoo/kafka-manager
Note that the service is internal only, so use kubectl port-forward
=> Adds yahoo/kafka-manger

50kafka.yml
As suggested in https://github.com/Yolean/kubernetes-kafka/issues/73.
Causes warnings in logs, as before.
=> Use Kubernetes native TCP readiness probe for kafka

kafka/50kafka.yml, zookeeper/50pzoo.yml, zookeeper/51zoo.yml
#55 would revert this.
For discussions on this topic, see the [automation](https://github.com/Yolean/kubernetes-kafka/labels/automation) label.
=> Disables RollingUpdate, i.e. reverts to pre-1.7 behavior

kafka/50kafka.yml
This seems to be the common ground between different monitoring approaches, such as an export sidecar (#49) or additional tooling (#83).
=> Enable broker JMX_PORT 5555

kafka/50kafka.yml, kafka/test/kafkacat.yml, kafka/test/produce-consume.yml, zookeeper/50pzoo.yml
I noticed a few thing that could be cleaned up, like the duplicate spec notations, and using the bootstrap service in the tests, since this is the new preferred usage.
=> Minor cleanups

README.md, kafka/10broker-config.yml, rbac-namespace-default/pod-labler.yml
I [thought](https://github.com/Yolean/kubernetes-kafka/commit/096e3bdfba31d2918520011886a6a0d1f1b08c84) https://github.com/kubernetes/kubernetes/pull/55329 would make such labels obsolete, but seeing that k8s 1.9 sets for example `statefulset.kubernetes.io/pod-name: kafka-0` I think they complement each other.
Moreover #78 depends on the `kafka-broker-id` for the `./outsite-services/` per-broker service.
=> Fix rbac to set useful labels on broker pods from init script

configure/docker-storageclass-broker.yml, configure/docker-storageclass-zookeeper.yml
Docker for Mac is now shipping with support for both Docker Swarm and Kubernetes built-in. If you install the Edge version of docker, which there is a [good walk through of the steps here](https://rominirani.com/tutorial-getting-started-with-kubernetes-with-docker-on-mac-7f58467203fd).
However, the provisioner is slightly different, so I'm adding those here. I didn't update the documentation because it's pretty bleeding edge, so I'm not sure you want to advertise support yet. Not sure if it works with the outside service for instance.
If you've ever installed minikube then you'll have to switch out of that context into the DfM context otherwise kubectl will hang.
```
kubectl config use-context docker-for-desktop
kubectl apply -f configure/docker-storageclass-zookeeper.yml
kubectl apply -f …
```
=> Add Docker-for-mac k8s specific provisioners for StorageClass

kafka/10broker-config.yml
... before #117 gets into a release.
See https://github.com/Yolean/kubernetes-kafka/issues/136#issuecomment-361038298 for why.
Thanks @shrinandj
=> Move outside host info from labels to annotations

kafka/test/kafkacat.yml, kafka/test/produce-consume.yml
Should have been done in #107.
There's a timing issue in tests, see https://github.com/Yolean/kubernetes-kafka/issues/116#issuecomment-359548701, so maybe we should remove explicit topic creation. On the other hand it's interesting for #134. Pending a decision we can merge this PR.
=> Update test topic replication factor

kafka/10broker-config.yml, kafka/test/kafkacat.yml, kafka/test/produce-consume.yml, kafka/test/replication-config.yml, yahoo-kafka-manager/kafka-manager.yml
Based on @shrinandj's find in #139.
As explained in https://github.com/Yolean/kubernetes-kafka/issues/116#issuecomment-359548701 we'd like to keep min.insync.replicas=2.
What's odd is that the default, according to [docs](https://kafka.apache.org/documentation/#brokerconfigs), is 3. Also I guess this change won't affect a running kafka cluster.
This property isn't mentioned in https://kafka.apache.org/documentation/#prodconfig.
There was a change in [0.11](https://kafka.apache.org/documentation/#upgrade_1100_notable): "The offsets.topic.replication.factor broker config is now enforced upon auto topic creation."
This PR quite possibly needs
- https://github.com/Yolean/kubernetes-kafka/pull/95/commits/49649e19bb7775165b6f5409211e05840f5c50ef
- Defaulted to 3 already, used for Kafka Connect …
=> Set internal replication factors to match default and min.insync.replicas

events-kube/events-kube-kafka.yml, events-kube/test/events-topic.yml
Partially address #109, with curl errors displayed (in brief) and WIP less unreadiness for the test when cluster is idle.
=> Improve robustness of events-kube test

README.md, kafka/10broker-config.yml, kafka/50kafka.yml, zookeeper/10zookeeper-config.yml, zookeeper/50pzoo.yml, zookeeper/51zoo.yml
I ran into an issue when deploying this onto our Tectonic kubernetes cluster. It turns out that the ConfigMap volumes are mounted read-only. I'm unsure if this is standard kubernetes behavior, but minikube does not do the same thing; it allows modification of the configmap files. Glancing at kubernetes code, it appears it *should* be mounted read-only.
So to fix this, I made a new emptyDir volume for where the config should go and then make the init containers copy the configmap files before they modify them.
=> cp configmap elements over to config volume as configmap vol is RO

kafka/10broker-config.yml
Increase transparency.
Based on @StevenACoffman's ideas around https://github.com/Yolean/kubernetes-kafka/issues/116#issuecomment-364484111.
=> Use Kafka config defaults as much as possible

kafka/50kafka.yml
Reverted the upgrade in #171.
With support for dynamic config stored in zookeeper it should be possible to do #78 through the CLI instead of init script changes. That in turn makes it likely that no one needs to edit the init script, in which case it can move to a regular entrypoint in a docker build such as #155. In particular if we can find a way to do #41 without kubectl access.
=> Kafka 1.1.0

outside-services/README.md
=> Outside access over hostport documented

events-kube/topic-create.yaml, kafka/10broker-config.yml
See the commit comment for why.
=> Disable automatic topic creation

kafka/10broker-config.yml
The number 12 was chosen to support an even load.
Counts of 2, 3, 4 and 6 are reasonable for both replicas and consumer group members.
At the same time we didn't want a high default number because the sample config file
mentions "more files across the brokers".
The reason for doing this change is that clients should not assume ordering guarantees unless designed for.
With #221 we won't use this default a lot, but maybe in the "not designed for" cases.
=> Topics now get 12 partitions by default

kafka/10broker-config.yml, zookeeper/10zookeeper-config.yml
Fixes #168, possibly avoiding unexpected states for example at transient kubectl errors
=> Crash loop intentionally if any command in an init script fails

README.md, avro-tools/rest.yml, avro-tools/schemas.yml, avro-tools/test/rest-curl.yml, events-kube/events-kube-kafka.yml, kafka/50kafka.yml, kafka/test/kafkacat.yml, kafka/test/produce-consume.yml, kafka/test/replication-config.yml, linkedin-burrow/burrow.yml, maintenance/preferred-replica-election-job.yml, maintenance/reassign-paritions-job.yml, maintenance/replication-factor-increase-job.yml, maintenance/test/replicated-partitions.yml, pixy/pixy.yml, prometheus/50-kafka-jmx-exporter-patch.yml, yahoo-kafka-manager/kafka-manager.yml, zookeeper/50pzoo.yml, zookeeper/51zoo.yml
Thanks to @mikenorgate for [alerting me](https://github.com/solsson/dockerfiles/pull/18) on why the zookeeper upgrade is important. We haven't applied this in production yet though.
Edit: Yolean never did the upgrade to 2.0.0 so I didn't merge. Now this PR is instead for Kafka 2.1.0 on Java 11 with images from https://github.com/solsson/dockerfiles/pull/19. It's clearly a destabilization, motivated by the importance of native support for containers in Java.
While destabilizing we will also merge other potentially breaking changes, as tracked by the 5.0 milestone.
=> Upgrade to Kafka 2.0.0 and Zookeeper 3.4.13

kafka/50kafka.yml, zookeeper/50pzoo.yml, zookeeper/51zoo.yml
Any votes on this? No need to do `kubectl delete` manually, but on the other hand the pod restart sequence may come as a surprise. Also I think it requires Kubernetes 1.7.
=> Trigger upgrades automatically on statefulset change

kafka/50kafka.yml, zookeeper/50pzoo.yml, zookeeper/51zoo.yml
Is there any reason to keep using OrderedReady with either Kafka or Zookeeper? We still get ordered rolling updates after #55. The problem with OrderedReady is that for `kafka` and `pzoo` if the zone with the volume for index `0` is unavailable none of the other pods can be restarted.
@sibtainabbas10 I noticed you used `Parallel` in #28 back in January. Have you seen any issues?
=> Switch to Parallel start for Kafka and Zookeeper

README.md, zookeeper/10zookeeper-config.yml, zookeeper/50pzoo.yml, zookeeper/51zoo.yml
Topic information, though not the contents kept in Kafka, would be lost if all zookeeper pods had been down at the same time. Only the snapshots were actually saved to the persistent volume.
According to https://zookeeper.apache.org/doc/r3.4.13/zookeeperAdmin.html#sc_dataFileManagement "ZooKeeper can recover using this snapshot".
The regression probably dates back to https://github.com/Yolean/kubernetes-kafka/commit/ccb9e5df12e5dbe70f243432d1613bd101b35630 which was released with v2.0.0.
=> Fix Zookeeper persistence

zookeeper/21zoo-service.yml
The destabilization effort with v5.0.0 is going great :)
I didn't notice this flaw until I experimented with scaling for https://github.com/Yolean/kubernetes-kafka/pull/228#issuecomment-443536263. The label change in #191 should have been reflected in the `zoo` service. It would have been apparent if I watched the logs during testing, with errors like:
```
[2018-12-02 20:00:24,587] WARN Failed to resolve address: zoo-1.zoo (org.apache.zookeeper.server.quorum.QuorumPeer)
java.net.UnknownHostException: zoo-1.zoo
at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
at java.base/java.net.InetAddress.getAllByName(InetAddress.java:129 …
```
=> Fix v5.0 regression that left zoo pods unreachable

zookeeper/10zookeeper-config.yml, zookeeper/50pzoo.yml, zookeeper/51zoo.yml
#227 for a v4.3.1 release, fixing #89, with an upgrade path to migrate your zookeeper state. Recovery from snapshots is an alternative, but I haven't looked into that.
v5.0.0 hasn't been out long enough for anyone to run anything important on, I suppose. Thus we should focus on how to migrate a 4.3.0 installation, that might have been running since v2.0.0. After this upgrade I think that it'll be a straightforward `kubectl replace` to go to v5.0.1.
=> Upgrade path for the zookeeper persistence issue

avro-tools/test/rest-curl.yml, cruise-control/topic-create.yml, kafka/50kafka.yml, kafka/test/kafkacat.yml, kafka/test/produce-consume.yml, maintenance/preferred-replica-election-job.yml, maintenance/reassign-paritions-job.yml, maintenance/replication-factor-increase-job.yml, maintenance/test/replicated-partitions.yml, update-kafka-image.sh, zookeeper/50pzoo.yml, zookeeper/51zoo.yml
Those who use java clients should take note of the improved handling of broker pod rotation: https://issues.apache.org/jira/browse/KAFKA-7755
=> Bump Kafka to 2.1.1

README.md, kafka/kustomization.yaml, variants/as-is/kustomization.yaml, variants/scale-1/kafka.yaml, variants/scale-1/kustomization.yaml, variants/scale-1/zookeeper.yaml, variants/scale-2/kafka.yaml, variants/scale-2/kustomization.yaml, variants/scale-2/zookeeper.yaml, zookeeper/10zookeeper-config.yml, zookeeper/kustomization.yaml
Useful for things like custom images, number of replicas, env etc.
=> Introduce a Kustomization concept

README.md, variants/scale-1-ephemeral/kafka-scale1-overrides.json, variants/scale-1-ephemeral/kafka.yaml, variants/scale-1-ephemeral/kustomization.yaml, variants/scale-1-ephemeral/zookeeper.yaml, variants/scale-1/kafka-scale1-overrides.json, variants/scale-1/kustomization.yaml
=> Fix replication factor for scale-1 variant, and add an -ephemeral variant

variants/scale-2/kafka-scale2-overrides.json, variants/scale-2/kustomization.yaml, variants/scale-2/zookeeper.yaml, variants/scale-3-5-nopzoo/kustomization.yaml, variants/scale-3-5-nopzoo/only-zoo-5.yaml
With storage class name abstracted out (#270) there's no reason other than backwards compatibility to keep pzoo. Except maybe if it helps in maintenance situations. Scaling zookeeper is a bit tricky due to all pods containing a static list of zk instances' DNS names.
I think this fixes #276, which is a duplicate of #123.
=> Fix the scale-2 variant and phase out pzoo

kafka/10broker-config.yml
Use bash arithmetic operation rather than string concatenation to compute OUTSIDE_PORT.
This allows supporting arbitrary number of brokers.
This is my proposal for #285
=> Support more than 10 brokers

kafka/50kafka.yml, zookeeper/50pzoo.yml, zookeeper/51zoo.yml
Clusters without a default storage class can get one globally using:
```
kubectl patch storageclass NAME -p "{\"metadata\":{\"annotations\":{\"storageclass.kubernetes.io/is-default-class\":\"true\"}}}"
```
Note that existing statefulsets can't be upgraded with this change. Apply will result in `spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`. When you already have volumes it's better to override storageclass like for example the GKE variant does: https://github.com/Yolean/kubernetes-kafka/blob/v6.0.3/variants/gke-regional/kustomization.yaml#L4 and https://github.com/Yolean/kubernetes-kafka/blob/v6.0.3/variants/gke-regional/gke-storageclass-broker-pd.yaml
=> Use default storage class

cruise-control/20kafka-broker-reporter-patch.yml
In this container, running 
`echo -e "\n\nmetric.reporters = com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter" | tee -a /etc/kafka/server.properties`
Returns
```
group.initial.rebalance.delay.ms=8000-e
metric.reporters = com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter
```
I believe sh is having some unexpected behavior when using the `-e` flag, but this command functions as intended when using bash. Bash is already included in this container.
=> Echo not working properly with "-e" in sh

variants/dev-small/kustomization.yaml, variants/scale-1/kustomization.yaml, variants/scale-2/kustomization.yaml
Hi there. I had trouble using these variants without adding these bits.
Without this change, these kustomiations fail to apply their patches
with errors like:
```
Error: no matches for OriginalId apps_v1_StatefulSet|~X|kafka; no
matches for CurrentId apps_v1_StatefulSet|~X|kafka; failed to find
unique target for patch apps_v1_StatefulSet|kafka
```
=> Add namespace to kustomizations

kafka/10broker-config.yml, variants/advertise-pod-ip/kafka.yaml, variants/advertise-pod-ip/kustomization.yaml
... and demonstrate how to advertise pod-IPs instead of the default `kafka-X.broker.kafka.svc.cluster.local:9092`.
=> Allow override of listener name

README.md, avro-tools/test/rest-curl.yml, cruise-control/50cruise-control.yml, kafka/50kafka.yml, kafka/test/kafkacat.yml, kafka/test/produce-consume.yml, maintenance/preferred-replica-election-job.yml, maintenance/reassign-paritions-job.yml, maintenance/replication-factor-increase-job.yml, maintenance/test/replicated-partitions.yml, yahoo-kafka-manager/kafka-manager.yml, zookeeper/10zookeeper-config.yml, zookeeper/50pzoo.yml, zookeeper/51zoo.yml
Highlights for us include:
- Consume from nearest replica, https://issues.apache.org/jira/browse/KAFKA-8443. Until now #41 was good for resilience, but now it might also help performance.
- We could have a leader election job, https://issues.apache.org/jira/browse/KAFKA-8286
- Dynamic log levels, could also be a job, https://issues.apache.org/jira/browse/KAFKA-7800
- We could possibly speed up some automated group consumer setups thanks to https://issues.apache.org/jira/browse/KAFKA-7471
- Topic creation jobs no longer _need_ to decide on replication factor and partitions, https://issues.apache.org/jira/browse/KAFKA-8305, which helps when we want to reuse automation across prod and development
=> Kafka 2.4.0

kafka/20dns.yml, kafka/50kafka.yml
This allows DNS names to be used in args interpolation, for example:
```yaml
- name: broker
env:
- name: POD_NAME
valueFrom:
fieldRef:
fieldPath: metadata.name
args:
- /etc/kafka/server.properties.$(POD_NAME)
- --override
-   listeners=PLAINTEXT://$(POD_NAME).kafka:9092
```
=> Rename the statefulset's headless service from broker to kafka

cruise-control/topic-create.yml, events-kube/topic-create.yaml, kafka/test/kafkacat.yml, kafka/test/produce-consume.yml
Investigates #323.
We should transition from --zookeeper to --bootstrap-server, but keep idempotence which means we'll probably need something like https://github.com/solsson/dockerfiles/blob/native/native/cli-scripts/kafka-topics_ifnotexists.sh.
=> Make sure topic create jobs use broker defaults

zookeeper/50pzoo.yml, zookeeper/51zoo.yml
kubectl describe on our zookeeper pods occasionally logged `Warning  Unhealthy  12s (x18 over 3m32s)  kubelet            Readiness probe errored: rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 1s exceeded: context deadline exceeded`. The Kafka cluster was still healthy, but we noticed that on Containerd nodes every such timeout left a process like this one:
```
root     2973844   16185  0 Feb10 ?        00:00:00 [sh] <defunct>
```
(on newer kafka clusters the user is [nonroot](https://github.com/Yolean/kubernetes-kafka/tree/master/nonroot) instead of root)
These processes stayed around forever, so that long lived nodes eventuall hit their thread limit. The reason we hadn't noticed the issue earlier was that, until recently, all our long lived nodes ran …
=> Fix Zookeeper readiness probe timeouts

kafka/10broker-config.yml
Deprecation notice: https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#failure-domainbetakubernetesiozone
=> Use k8s 1.17+ topology.kubernetes.io/zone for broker.rack
